#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
export WM_CONTINUE_ON_ERROR=true                    # Optional unit
. ${WM_PROJECT_DIR:?}/wmake/scripts/cmakeFunctions  # Cmake functions
# . ${WM_PROJECT_DIR:?}/wmake/scripts/wmake.cmake-args
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Copyright (C) 2020 OpenCFD Ltd.
# This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
#
# Note
#     - use '-prefix=..' to define installation prefix (default: FOAM_LIBBIN)
#------------------------------------------------------------------------------

# Default is openfoam (FOAM_LIBBIN)
: "${CMAKE_INSTALL_PREFIX:=${FOAM_LIBBIN%/*}}"

unset cmakeOpts
if [ -n "$CMAKE_INSTALL_PREFIX" ]
then
    export CMAKE_INSTALL_PREFIX
    cmakeOpts="-DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX"
fi

#------------------------------------------------------------------------------

echo "======================================================================"
echo "${PWD##*/} : $PWD"
echo

unset depend senseiDebug

if [ -d "$Sensei_DIR" ]
then
    depend="Sensei_DIR=$Sensei_DIR"
fi


if [ "$targetType" = objects ]
then
    depend=ignore
elif [ -n "$depend" ]
then
    if have_cmake
    then
        echo "sensei prefix : $CMAKE_INSTALL_PREFIX"
        cmakeVersionedInstall "$depend" "$PWD" $cmakeOpts || {
            echo
            echo "    WARNING: incomplete build of sensei"
            echo
        }
    else
        echo "WARNING: skipped - needs cmake"
    fi
else
    echo "WARNING: skip sensei"
fi

echo "======================================================================"

# -----------------------------------------------------------------------------
