/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | www.openfoam.com
     \\/     M anipulation  |
-------------------------------------------------------------------------------
    Copyright (C) 2018 OpenCFD Ltd.
    Copyright (C) 2018 CINECA
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
\*---------------------------------------------------------------------------*/

namespace Foam
{
namespace sensei
{
namespace bridge
{
//  int initialize(size_t nblocks, size_t n_local_blocks, float *origin,
//   float *spacing, int domain_shape_x, int domain_shape_y, int domain_shape_z,
//   int *gid, int *from_x, int *from_y, int *from_z, int *to_x, int *to_y,
//   int *to_z, int *shape, int ghostLevels, const std::string& config_file);
//
// void set_data(int gid, float* data);
// void set_particles(int gid, const std::vector<Particle> &particles);
//
// void execute(long step, float time);
//
// void finalize();

}
}
}
